apiVersion: v1
kind: Service
metadata:
  name: kube-sample-service
spec:
  selector:
    app: kube-sample
  ports:
    - protocol: TCP
      port: 8181
      targetPort: 3000
      nodePort: 32147
  type: LoadBalancer

