apiVersion: v1
kind: Service
metadata:
  name: vault-service
spec:
  selector:
    app: vault
  ports:
    - protocol: TCP
      port: 8181
      targetPort: 8200
      nodePort: 32148
  type: LoadBalancer

