apiVersion: v1
kind: Service
metadata:
  name: oidc-service
spec:
  selector:
    app: oidc
  ports:
    - protocol: TCP
      port: 8181
      targetPort: 3000
      nodePort: 32149
  type: LoadBalancer

